In [1]:
data=[80,90,45,70,60,85,95,75,65,55]
print(type(data))

<class 'list'>


In [2]:
# pip install numpy
import numpy as np
data1=np.array(data)

In [3]:
print(type(data1))

<class 'numpy.ndarray'>


In [4]:
print(data)
print(data1)

[80, 90, 45, 70, 60, 85, 95, 75, 65, 55]
[80 90 45 70 60 85 95 75 65 55]


In [7]:
Hindi=[78,75,90,85,80,95,88,92,82,91]
print(len(Hindi))
Math=[80,90,45,70,60,85,95,75,65,55]
print(len(Math))
Total=Hindi+Math
print(Total)
print(len(Total))

10
10
[78, 75, 90, 85, 80, 95, 88, 92, 82, 91, 80, 90, 45, 70, 60, 85, 95, 75, 65, 55]
20


In [8]:
Total_Marks=np.array(Hindi)+np.array(Math)
print(Total_Marks)

[158 165 135 155 140 180 183 167 147 146]


In [9]:
np.mean(Total_Marks)

np.float64(157.6)

In [13]:
Hindi=np.array(Hindi)
Math=np.array(Math)
print(Hindi)

[78 75 90 85 80 95 88 92 82 91]


In [14]:
np.max(Hindi)

np.int64(95)

In [22]:
a=np.array(["Pyhton","Java","C++",1,2,3.5])

In [23]:
print(type(a))

<class 'numpy.ndarray'>


In [24]:
a.ndim

1

In [25]:
a

array(['Pyhton', 'Java', 'C++', '1', '2', '3.5'], dtype='<U32')

In [21]:
Hindi.dtype

dtype('int64')

In [30]:
values=np.array(['a',5,6.7,True,3+5j])

In [31]:
values

array(['a', '5', '6.7', 'True', '(3+5j)'], dtype='<U64')

In [34]:
Total_Marks.ndim

1

In [35]:
Total_Marks.shape

(10,)

In [4]:
import numpy as np
marks=np.array([
    [80,90,45,70,60,85,95,75,65,55],
    [78,75,90,85,80,95,88,92,82,91]
])

marks[1:2,0:1]

array([[78]])

In [39]:
print("Dimension Of marks:", marks.ndim,'D')
print("Shape Of marks:", marks.shape)
print("Size Of marks:", marks.size)
print("Data Type Of marks:", marks.dtype)
print("Data Type Of marks:", type(marks))

Dimension Of marks: 2 D
Shape Of marks: (2, 10)
Size Of marks: 20
Data Type Of marks: int64
Data Type Of marks: <class 'numpy.ndarray'>


In [40]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

In [48]:
marks1=np.array(
    [
    [80,90,45,70,60,85,95,75,65,55],
    [78,75,90,85,80,95,88,92,82,91], 
    ]
    )

In [49]:
marks1.ndim

2

In [50]:
marks2=np.array(    
[
        [10,20,3,0,5,6,7,8,9,1],
        [50,60,70,80,90,100,110,120,130,140],
    ]
    
    )

In [52]:
marks2.ndim

2

In [57]:
marks1=np.array([
    [
        [80,90,45,70,60,85,95,75,65,55],
        [78,75,90,85,80,95,88,92,82,91]
    ],

    [
        [10,20,3,0,5,6,7,8,9,1],
        [50,60,70,80,90,100,110,120,130,140]
    ]
    
    ])

In [53]:
arrnew=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arrnew.ndim

3

In [58]:
marks1.ndim

3

In [59]:
Hindi

array([78, 75, 90, 85, 80, 95, 88, 92, 82, 91])

In [63]:
print(Hindi[4])

80


In [67]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

In [86]:
a=list([[[marks[0][7],marks[1][0]]]])

In [87]:
print(a)

[[[np.int64(75), np.int64(78)]]]


In [94]:
a=[marks[0][7],marks[1][0]]

In [95]:
a

[np.int64(75), np.int64(78)]

In [103]:
a=[marks[0][7],marks[1][0]]
print(a)

[np.int64(75), np.int64(78)]


In [98]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

IndexError: index 7 is out of bounds for axis 0 with size 2

In [104]:
a=[int(marks[0][7]),int(marks[1][0])]

In [106]:
a.append

<function list.append(object, /)>

In [1]:
marks[1:2,0:1]

NameError: name 'marks' is not defined

In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt

# =========================================================
# TASK SCHEDULING USING REINFORCEMENT LEARNING (Q-LEARNING)
# =========================================================

# -----------------------------
# ENVIRONMENT SETTINGS
# -----------------------------

NUM_SERVERS = 3
NUM_TASKS = 20
EPISODES = 500

ALPHA = 0.1      # Learning Rate
GAMMA = 0.9      # Discount Factor
EPSILON = 0.2    # Exploration Rate

# -----------------------------
# CREATE SERVERS
# -----------------------------

servers = [0 for _ in range(NUM_SERVERS)]

# Example:
# [0,0,0]
# Means all servers have zero load

# -----------------------------
# CREATE Q TABLE
# -----------------------------

# State Space:
# Server loads between 0-20

Q = np.zeros((21, 21, 21, NUM_SERVERS))

# Shape:
# [server1_load][server2_load][server3_load][action]

# -----------------------------
# TRACKING VARIABLES
# -----------------------------

episode_rewards = []
waiting_times = []

# =========================================================
# FUNCTION: GENERATE TASKS
# =========================================================

def generate_task():

    execution_time = random.randint(1, 10)

    priority = random.randint(1, 5)

    task = {
        "execution_time": execution_time,
        "priority": priority
    }

    return task

# =========================================================
# FUNCTION: GET CURRENT STATE
# =========================================================

def get_state(server_loads):

    state = tuple(
        min(load, 20) for load in server_loads
    )

    return state

# =========================================================
# FUNCTION: CHOOSE ACTION
# =========================================================

def choose_action(state):

    # Exploration
    if random.uniform(0,1) < EPSILON:

        return random.randint(0, NUM_SERVERS-1)

    # Exploitation
    else:

        return np.argmax(Q[state])

# =========================================================
# FUNCTION: CALCULATE REWARD
# =========================================================

def calculate_reward(load, execution_time):

    waiting_time = load

    reward = -(waiting_time + execution_time)

    return reward, waiting_time

# =========================================================
# TRAINING LOOP
# =========================================================

for episode in range(EPISODES):

    # Reset Server Loads
    server_loads = [0,0,0]

    total_reward = 0
    total_waiting = 0

    # -----------------------------
    # TASK LOOP
    # -----------------------------

    for _ in range(NUM_TASKS):

        # Generate Task
        task = generate_task()

        execution_time = task["execution_time"]

        # Current State
        state = get_state(server_loads)

        # Choose Server
        action = choose_action(state)

        # Current Load
        current_load = server_loads[action]

        # Calculate Reward
        reward, waiting_time = calculate_reward(
            current_load,
            execution_time
        )

        # Assign Task to Server
        server_loads[action] += execution_time

        # Next State
        next_state = get_state(server_loads)

        # Q-Learning Update
        old_value = Q[state][action]

        next_max = np.max(Q[next_state])

        new_value = old_value + ALPHA * (
            reward + GAMMA * next_max - old_value
        )

        Q[state][action] = new_value

        # Update Metrics
        total_reward += reward
        total_waiting += waiting_time

    # Store Episode Results
    episode_rewards.append(total_reward)

    avg_waiting = total_waiting / NUM_TASKS

    waiting_times.append(avg_waiting)

    # Print Progress
    if episode % 50 == 0:

        print(f"Episode: {episode}")
        print(f"Total Reward: {total_reward}")
        print(f"Average Waiting Time: {avg_waiting:.2f}")
        print("-"*40)

# =========================================================
# TEST TRAINED AGENT
# =========================================================

print("\n==============================")
print("TESTING TRAINED AGENT")
print("==============================")

server_loads = [0,0,0]

for i in range(10):

    task = generate_task()

    state = get_state(server_loads)

    action = np.argmax(Q[state])

    execution_time = task["execution_time"]

    print(f"\nTask {i+1}")
    print(f"Execution Time: {execution_time}")
    print(f"Assigned Server: {action+1}")

    server_loads[action] += execution_time

    print(f"Updated Server Loads: {server_loads}")

# =========================================================
# PLOT 1: REWARD VS EPISODES
# =========================================================

plt.figure(figsize=(10,5))

plt.plot(episode_rewards)

plt.title("Reward vs Episodes")

plt.xlabel("Episodes")

plt.ylabel("Total Reward")

plt.grid(True)

plt.show()

# =========================================================
# PLOT 2: WAITING TIME VS EPISODES
# =========================================================

plt.figure(figsize=(10,5))

plt.plot(waiting_times)

plt.title("Average Waiting Time vs Episodes")

plt.xlabel("Episodes")

plt.ylabel("Waiting Time")

plt.grid(True)

plt.show()

In [ ]:
1. Zeros
2. Ones
3. Full
4. Eye
5. Random
6. Arange
7. Linspace
5. Random Numbers
6. reshape
7. Indexing and Slicing 
8

In [8]:
import numpy as np

a=np.zeros(5,dtype=np.int64)

In [9]:
a

array([0, 0, 0, 0, 0])

In [10]:
print(a.dtype)

int64


In [11]:
a

array([0, 0, 0, 0, 0])

In [32]:
d2=np.zeros((3,4),dtype=np.int64)+6

In [33]:
d2
d2

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [23]:
d2array=np.ones((3,4),dtype=np.int64)

In [25]:
d2array*=5

In [26]:
d2array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [34]:
arr=np.full((2,2),8)
print(arr)

[[8 8]
 [8 8]]


In [36]:
arr1=np.arange(5,20)
print(len(arr1))

15


In [37]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
arr1=np.arange(5,20,2)
print(len(arr1))

8


In [40]:
arr1

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
arr3=np.linspace(10,50,8)

In [44]:
arr3

array([10.        , 15.71428571, 21.42857143, 27.14285714, 32.85714286,
       38.57142857, 44.28571429, 50.        ])

In [46]:
a=50.00
b=44.28571429
c=38.57142857
print(b-c)

5.7142857199999995


In [58]:
import numpy as np
data=np.random.rand(1,5)
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [52]:
import numpy as np
data=np.random.randint(1,100,1)
data

array([36], dtype=int32)

In [61]:
data.shape

(1, 5)

In [60]:
data.ndim

2

In [59]:
data.shape

(1, 5)

In [62]:
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [65]:
list2=[[4,45,56,5]]
list2=np.array(list2)

In [66]:
list2.ndim

2

In [67]:
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [70]:
arr=np.array([1,2,3,4,5,6])
arr.ndim


1

In [71]:
new_arr=np.reshape(arr,(2,3))

In [72]:
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [84]:
arr=arr.reshape(3,2)

In [83]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
# Find 1st element of 0st row
print(arr[0][0])
# Find 2nd element of 1st row
print(arr[1][1])
print(arr[2][0])

1
4
5


In [101]:
find_arr=[int(arr[0][0]),int(arr[1][1]),int(arr[2][0])]

In [102]:
print(find_arr)

[1, 4, 5]


In [103]:
a=[5000,4000,8000]
b=[]
for i in a:
    b.append(i+5000)
print(b)

[10000, 9000, 13000]


In [104]:
salary=np.array(a)

In [105]:
print(salary+8000)

[13000 12000 16000]


In [106]:
name_list=["Vishnu","Ravi","Suresh"]
name=np.array(name_list)
print(name+" Kumar")

['Vishnu Kumar' 'Ravi Kumar' 'Suresh Kumar']


In [107]:
updated_name=[]
for i in name:
    updated_name.append(i+" Kumar")
print(updated_name)

['Vishnu Kumar', 'Ravi Kumar', 'Suresh Kumar']


In [110]:
salary
second_salary_data=np.random.randint(180000,250000,10)

In [111]:
second_salary_data

array([212289, 181653, 239887, 206854, 205316, 191397, 189878, 180915,
       199102, 226481], dtype=int32)

In [112]:
salary

array([5000, 4000, 8000])

In [113]:
final_salary=np.concatenate((salary,second_salary_data))

In [114]:
final_salary

array([  5000,   4000,   8000, 212289, 181653, 239887, 206854, 205316,
       191397, 189878, 180915, 199102, 226481])

In [116]:
final_salary[0:3]=np.random.randint(300000,500000,3)

In [117]:
final_salary

array([382554, 319769, 393639, 212289, 181653, 239887, 206854, 205316,
       191397, 189878, 180915, 199102, 226481])

In [123]:
print(final_salary[final_salary>250000])

[382554 319769 393639]


In [125]:
print(max(final_salary))
print(min(final_salary))
print(np.mean(final_salary))
print(np.median(final_salary))

393639
180915
240748.76923076922
206854.0


In [129]:
mask=final_salary>250000
print(final_salary[mask])

[382554 319769 393639]
