In [1]:
data=[80,90,45,70,60,85,95,75,65,55]
print(type(data))

<class 'list'>


In [2]:
# pip install numpy
import numpy as np
data1=np.array(data)

In [3]:
print(type(data1))

<class 'numpy.ndarray'>


In [4]:
print(data)
print(data1)

[80, 90, 45, 70, 60, 85, 95, 75, 65, 55]
[80 90 45 70 60 85 95 75 65 55]


In [7]:
Hindi=[78,75,90,85,80,95,88,92,82,91]
print(len(Hindi))
Math=[80,90,45,70,60,85,95,75,65,55]
print(len(Math))
Total=Hindi+Math
print(Total)
print(len(Total))

10
10
[78, 75, 90, 85, 80, 95, 88, 92, 82, 91, 80, 90, 45, 70, 60, 85, 95, 75, 65, 55]
20


In [8]:
Total_Marks=np.array(Hindi)+np.array(Math)
print(Total_Marks)

[158 165 135 155 140 180 183 167 147 146]


In [9]:
np.mean(Total_Marks)

np.float64(157.6)

In [13]:
Hindi=np.array(Hindi)
Math=np.array(Math)
print(Hindi)

[78 75 90 85 80 95 88 92 82 91]


In [14]:
np.max(Hindi)

np.int64(95)

In [22]:
a=np.array(["Pyhton","Java","C++",1,2,3.5])

In [23]:
print(type(a))

<class 'numpy.ndarray'>


In [24]:
a.ndim

1

In [25]:
a

array(['Pyhton', 'Java', 'C++', '1', '2', '3.5'], dtype='<U32')

In [21]:
Hindi.dtype

dtype('int64')

In [30]:
values=np.array(['a',5,6.7,True,3+5j])

In [31]:
values

array(['a', '5', '6.7', 'True', '(3+5j)'], dtype='<U64')

In [34]:
Total_Marks.ndim

1

In [35]:
Total_Marks.shape

(10,)

In [4]:
import numpy as np
marks=np.array([
    [80,90,45,70,60,85,95,75,65,55],
    [78,75,90,85,80,95,88,92,82,91]
])

marks[1:2,0:1]

array([[78]])

In [39]:
print("Dimension Of marks:", marks.ndim,'D')
print("Shape Of marks:", marks.shape)
print("Size Of marks:", marks.size)
print("Data Type Of marks:", marks.dtype)
print("Data Type Of marks:", type(marks))

Dimension Of marks: 2 D
Shape Of marks: (2, 10)
Size Of marks: 20
Data Type Of marks: int64
Data Type Of marks: <class 'numpy.ndarray'>


In [40]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

In [48]:
marks1=np.array(
    [
    [80,90,45,70,60,85,95,75,65,55],
    [78,75,90,85,80,95,88,92,82,91], 
    ]
    )

In [49]:
marks1.ndim

2

In [50]:
marks2=np.array(    
[
        [10,20,3,0,5,6,7,8,9,1],
        [50,60,70,80,90,100,110,120,130,140],
    ]
    
    )

In [52]:
marks2.ndim

2

In [57]:
marks1=np.array([
    [
        [80,90,45,70,60,85,95,75,65,55],
        [78,75,90,85,80,95,88,92,82,91]
    ],

    [
        [10,20,3,0,5,6,7,8,9,1],
        [50,60,70,80,90,100,110,120,130,140]
    ]
    
    ])

In [53]:
arrnew=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arrnew.ndim

3

In [58]:
marks1.ndim

3

In [59]:
Hindi

array([78, 75, 90, 85, 80, 95, 88, 92, 82, 91])

In [63]:
print(Hindi[4])

80


In [67]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

In [86]:
a=list([[[marks[0][7],marks[1][0]]]])

In [87]:
print(a)

[[[np.int64(75), np.int64(78)]]]


In [94]:
a=[marks[0][7],marks[1][0]]

In [95]:
a

[np.int64(75), np.int64(78)]

In [103]:
a=[marks[0][7],marks[1][0]]
print(a)

[np.int64(75), np.int64(78)]


In [98]:
marks

array([[80, 90, 45, 70, 60, 85, 95, 75, 65, 55],
       [78, 75, 90, 85, 80, 95, 88, 92, 82, 91]])

IndexError: index 7 is out of bounds for axis 0 with size 2

In [104]:
a=[int(marks[0][7]),int(marks[1][0])]

In [106]:
a.append

<function list.append(object, /)>

In [1]:
marks[1:2,0:1]

NameError: name 'marks' is not defined

In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt

# =========================================================
# TASK SCHEDULING USING REINFORCEMENT LEARNING (Q-LEARNING)
# =========================================================

# -----------------------------
# ENVIRONMENT SETTINGS
# -----------------------------

NUM_SERVERS = 3
NUM_TASKS = 20
EPISODES = 500

ALPHA = 0.1      # Learning Rate
GAMMA = 0.9      # Discount Factor
EPSILON = 0.2    # Exploration Rate

# -----------------------------
# CREATE SERVERS
# -----------------------------

servers = [0 for _ in range(NUM_SERVERS)]

# Example:
# [0,0,0]
# Means all servers have zero load

# -----------------------------
# CREATE Q TABLE
# -----------------------------

# State Space:
# Server loads between 0-20

Q = np.zeros((21, 21, 21, NUM_SERVERS))

# Shape:
# [server1_load][server2_load][server3_load][action]

# -----------------------------
# TRACKING VARIABLES
# -----------------------------

episode_rewards = []
waiting_times = []

# =========================================================
# FUNCTION: GENERATE TASKS
# =========================================================

def generate_task():

    execution_time = random.randint(1, 10)

    priority = random.randint(1, 5)

    task = {
        "execution_time": execution_time,
        "priority": priority
    }

    return task

# =========================================================
# FUNCTION: GET CURRENT STATE
# =========================================================

def get_state(server_loads):

    state = tuple(
        min(load, 20) for load in server_loads
    )

    return state

# =========================================================
# FUNCTION: CHOOSE ACTION
# =========================================================

def choose_action(state):

    # Exploration
    if random.uniform(0,1) < EPSILON:

        return random.randint(0, NUM_SERVERS-1)

    # Exploitation
    else:

        return np.argmax(Q[state])

# =========================================================
# FUNCTION: CALCULATE REWARD
# =========================================================

def calculate_reward(load, execution_time):

    waiting_time = load

    reward = -(waiting_time + execution_time)

    return reward, waiting_time

# =========================================================
# TRAINING LOOP
# =========================================================

for episode in range(EPISODES):

    # Reset Server Loads
    server_loads = [0,0,0]

    total_reward = 0
    total_waiting = 0

    # -----------------------------
    # TASK LOOP
    # -----------------------------

    for _ in range(NUM_TASKS):

        # Generate Task
        task = generate_task()

        execution_time = task["execution_time"]

        # Current State
        state = get_state(server_loads)

        # Choose Server
        action = choose_action(state)

        # Current Load
        current_load = server_loads[action]

        # Calculate Reward
        reward, waiting_time = calculate_reward(
            current_load,
            execution_time
        )

        # Assign Task to Server
        server_loads[action] += execution_time

        # Next State
        next_state = get_state(server_loads)

        # Q-Learning Update
        old_value = Q[state][action]

        next_max = np.max(Q[next_state])

        new_value = old_value + ALPHA * (
            reward + GAMMA * next_max - old_value
        )

        Q[state][action] = new_value

        # Update Metrics
        total_reward += reward
        total_waiting += waiting_time

    # Store Episode Results
    episode_rewards.append(total_reward)

    avg_waiting = total_waiting / NUM_TASKS

    waiting_times.append(avg_waiting)

    # Print Progress
    if episode % 50 == 0:

        print(f"Episode: {episode}")
        print(f"Total Reward: {total_reward}")
        print(f"Average Waiting Time: {avg_waiting:.2f}")
        print("-"*40)

# =========================================================
# TEST TRAINED AGENT
# =========================================================

print("\n==============================")
print("TESTING TRAINED AGENT")
print("==============================")

server_loads = [0,0,0]

for i in range(10):

    task = generate_task()

    state = get_state(server_loads)

    action = np.argmax(Q[state])

    execution_time = task["execution_time"]

    print(f"\nTask {i+1}")
    print(f"Execution Time: {execution_time}")
    print(f"Assigned Server: {action+1}")

    server_loads[action] += execution_time

    print(f"Updated Server Loads: {server_loads}")

# =========================================================
# PLOT 1: REWARD VS EPISODES
# =========================================================

plt.figure(figsize=(10,5))

plt.plot(episode_rewards)

plt.title("Reward vs Episodes")

plt.xlabel("Episodes")

plt.ylabel("Total Reward")

plt.grid(True)

plt.show()

# =========================================================
# PLOT 2: WAITING TIME VS EPISODES
# =========================================================

plt.figure(figsize=(10,5))

plt.plot(waiting_times)

plt.title("Average Waiting Time vs Episodes")

plt.xlabel("Episodes")

plt.ylabel("Waiting Time")

plt.grid(True)

plt.show()

In [ ]:
1. Zeros
2. Ones
3. Full
4. Eye
5. Random
6. Arange
7. Linspace
5. Random Numbers
6. reshape
7. Indexing and Slicing 
8

In [8]:
import numpy as np

a=np.zeros(5,dtype=np.int64)

In [9]:
a

array([0, 0, 0, 0, 0])

In [10]:
print(a.dtype)

int64


In [11]:
a

array([0, 0, 0, 0, 0])

In [32]:
d2=np.zeros((3,4),dtype=np.int64)+6

In [33]:
d2
d2

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [23]:
d2array=np.ones((3,4),dtype=np.int64)

In [25]:
d2array*=5

In [26]:
d2array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [34]:
arr=np.full((2,2),8)
print(arr)

[[8 8]
 [8 8]]


In [36]:
arr1=np.arange(5,20)
print(len(arr1))

15


In [37]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
arr1=np.arange(5,20,2)
print(len(arr1))

8


In [40]:
arr1

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
arr3=np.linspace(10,50,8)

In [44]:
arr3

array([10.        , 15.71428571, 21.42857143, 27.14285714, 32.85714286,
       38.57142857, 44.28571429, 50.        ])

In [46]:
a=50.00
b=44.28571429
c=38.57142857
print(b-c)

5.7142857199999995


In [58]:
import numpy as np
data=np.random.rand(1,5)
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [52]:
import numpy as np
data=np.random.randint(1,100,1)
data

array([36], dtype=int32)

In [61]:
data.shape

(1, 5)

In [60]:
data.ndim

2

In [59]:
data.shape

(1, 5)

In [62]:
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [65]:
list2=[[4,45,56,5]]
list2=np.array(list2)

In [66]:
list2.ndim

2

In [67]:
data

array([[0.85407553, 0.27298482, 0.18610454, 0.48238539, 0.15454701]])

In [70]:
arr=np.array([1,2,3,4,5,6])
arr.ndim


1

In [71]:
new_arr=np.reshape(arr,(2,3))

In [72]:
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [84]:
arr=arr.reshape(3,2)

In [83]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
# Find 1st element of 0st row
print(arr[0][0])
# Find 2nd element of 1st row
print(arr[1][1])
print(arr[2][0])

1
4
5


In [101]:
find_arr=[int(arr[0][0]),int(arr[1][1]),int(arr[2][0])]

In [102]:
print(find_arr)

[1, 4, 5]


In [103]:
a=[5000,4000,8000]
b=[]
for i in a:
    b.append(i+5000)
print(b)

[10000, 9000, 13000]


In [104]:
salary=np.array(a)

In [105]:
print(salary+8000)

[13000 12000 16000]


In [106]:
name_list=["Vishnu","Ravi","Suresh"]
name=np.array(name_list)
print(name+" Kumar")

['Vishnu Kumar' 'Ravi Kumar' 'Suresh Kumar']


In [107]:
updated_name=[]
for i in name:
    updated_name.append(i+" Kumar")
print(updated_name)

['Vishnu Kumar', 'Ravi Kumar', 'Suresh Kumar']


In [110]:
salary
second_salary_data=np.random.randint(180000,250000,10)

In [111]:
second_salary_data

array([212289, 181653, 239887, 206854, 205316, 191397, 189878, 180915,
       199102, 226481], dtype=int32)

In [112]:
salary

array([5000, 4000, 8000])

In [113]:
final_salary=np.concatenate((salary,second_salary_data))

In [114]:
final_salary

array([  5000,   4000,   8000, 212289, 181653, 239887, 206854, 205316,
       191397, 189878, 180915, 199102, 226481])

In [116]:
final_salary[0:3]=np.random.randint(300000,500000,3)

In [117]:
final_salary

array([382554, 319769, 393639, 212289, 181653, 239887, 206854, 205316,
       191397, 189878, 180915, 199102, 226481])

In [123]:
print(final_salary[final_salary>250000])

[382554 319769 393639]


In [125]:
print(max(final_salary))
print(min(final_salary))
print(np.mean(final_salary))
print(np.median(final_salary))

393639
180915
240748.76923076922
206854.0


In [129]:
mask=final_salary>250000
print(final_salary[mask])

[382554 319769 393639]


In [2]:
# Topic
# Reshapeping Array

import numpy as np
marks=np.array([80,75,90,60,85,65])
print(marks)


[80 75 90 60 85 65]


In [7]:
# 2 row 3 column
# [[80,75,90],   ----0
# [60,85,65]]------1

new_marks=marks.reshape(2,3)
print(new_marks)

[[80 75 90]
 [60 85 65]]


In [4]:
new_marks.ndim

2

In [5]:
# Flatten()
# 2D----1D
new_marks=new_marks.flatten()


In [8]:
print(new_marks)

[[80 75 90]
 [60 85 65]]


In [9]:
# Ravel()
updated_marks=new_marks.ravel()
print(updated_marks)



[80 75 90 60 85 65]


In [11]:
# Mathematical Functions
# average
# max
# standard deviation
# normalization
# Weekly Sales Data
sales=np.array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550])
print("Total Sales Amount:", np.sum(sales))
print("Average Daily Sales:", np.mean(sales))
print("Maximum Daily Sales:", np.max(sales))
print("Minimum Daily Sales:", np.min(sales))
print("Standard Deviation of Sales:", np.std(sales))



Total Sales Amount: 3250
Average Daily Sales: 325.0
Maximum Daily Sales: 550
Minimum Daily Sales: 100
Standard Deviation of Sales: 143.61406616345073


In [22]:
SALES_AMOUNT=[7,8,9,10,11,12]
sales_amount=np.array(SALES_AMOUNT)
average=np.median(sales_amount)
sd=np.std(sales_amount)
print(sd)

1.707825127659933


In [13]:
print(average)

9.5


In [ ]:
# xi-  X(avg)^2/6
x1     X      Ouput     X^2      
7      9.5     2.5      6.25
8      9.5     1.5      2.25
9      9.5     0.5      0.25
10     9.5     -0.5     0.25
11     9.5     -1.5     2.25
12     9.5     -2.5     6.25






In [24]:
import math
a=6.25+2.25+0.25+0.25+2.25+6.25
std=a/6
print(math.sqrt(std))

1.707825127659933


In [18]:
print(std)

2.9166666666666665


In [27]:
# # Normalization
# Age                Salary
# 21                  25000
# 25                  50000
# 30                  100000


import numpy as np
salary=np.array([250000,50000,100000,150000,200000,250000,300000,350000,400000,450000])
normaluized=(salary-np.min(salary))/(np.max(salary)-np.min(salary))
print(normaluized)

[0.5   0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [35]:
age=[45,62,42,35,15,14,18,19]
age=np.array(age)
# Z=age-mean/std
standardized_age=(age-np.mean(age))/np.std(age)

In [36]:
print(standardized_age)

[ 0.83844971  1.87507843  0.65551522  0.2286681  -0.99089511 -1.05187327
 -0.80796063 -0.74698246]


In [37]:
# Axis Concept


data=np.array(
[[65, 78, 33],
 [88, 56, 64],
 [78, 38, 49]]
)

# axis=0   ---column
# axis =1  -----row


print(np.sum(data,axis=0))

[231 172 146]


In [38]:
print(np.sum(data,axis=1))

[176 208 165]


In [40]:
# Joining Arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [41]:
# Vstack
# hstack
# 
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))    

[[1 2 3]
 [4 5 6]]


In [42]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [43]:
a=np.array([[1],[2]])
b=np.array([[3],[4]])
print(np.hstack((a,b)))

[[1 3]
 [2 4]]


In [44]:
print(np.vstack((a,b)))

[[1]
 [2]
 [3]
 [4]]


In [45]:
marks=np.array([85, 90, 78, 92, 88, 95, 80, 91, 87, 89])
# [pass,pass fail,pass]
result=np.where(marks>=80,"Pass","Fail")
print(result)

['Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [46]:
emails=np.array([1,0,1,1,0,1,1,0,1,1])
spam_mail=np.where(emails==0,"Spam","Not Spam")
print(spam_mail)

['Not Spam' 'Spam' 'Not Spam' 'Not Spam' 'Spam' 'Not Spam' 'Not Spam'
 'Spam' 'Not Spam' 'Not Spam']


In [49]:
count_spam=np.sum(emails==0)
print(count_spam)

3


In [50]:
not_spam=np.sum(emails==1)  

In [52]:
not_spam=np.sum(emails==1)
print(not_spam)

7


In [53]:
# Sorting,Unique,argmax(),argmin()
prices=np.array([2450,2510,2480,2430,2500])
sorted_prices=np.sort(prices)
print(sorted_prices)

[2430 2450 2480 2500 2510]


In [58]:
prices=np.array([2450,2510,2480,2430,2500])
sorted_prices=np.sort(prices)[::-1]

In [59]:
sorted_prices

array([2510, 2500, 2480, 2450, 2430])

In [62]:
data=np.array([10,20,30,40,50,40,50,30,78,40,50])
unique_values=np.unique(data)

In [63]:
unique_values

array([10, 20, 30, 40, 50, 78])

In [65]:
sales=np.array([1000, 150, 200, 250, 300, 350, 400, 450, 500, 550])
print(np.argmax(sales))

0


In [ ]:
Broadcasting
argmin
argmax
Statistics Operation
    mean
    median
    mode
    standard deviation
    variance
    percentile
    correlation


In [13]:
import numpy as np
marks=np.array([85, 90,90,80,72,65,78,72,88, 78, 92, 88, 95, 80, 91, 87, 89])
updated_marks=marks-5
print(updated_marks
      )

[80 85 85 75 67 60 73 67 83 73 87 83 90 75 86 82 84]


In [14]:
print(np.argmin(updated_marks))

5


In [15]:
print(np.argmax(updated_marks))

12


In [16]:
updated_marks

array([80, 85, 85, 75, 67, 60, 73, 67, 83, 73, 87, 83, 90, 75, 86, 82, 84])

In [17]:
import statistics as st
print("Average Marks is ",np.mean(updated_marks))
print("Average Marks is ",st.mode(updated_marks))

Average Marks is  78.52941176470588
Average Marks is  85


In [18]:
print(np.median(updated_marks))

82.0


In [20]:
print(np.sort(updated_marks))

[60 67 67 73 73 75 75 80 82 83 83 84 85 85 86 87 90]


In [21]:
array1=np.array([10,20,30,40])
std=np.std(array1)

In [22]:
print(std)

11.180339887498949


In [23]:
print(np.var(array1))

125.0


In [24]:
marks

array([85, 90, 90, 80, 72, 65, 78, 72, 88, 78, 92, 88, 95, 80, 91, 87, 89])

In [31]:
print(np.percentile(marks,25))

78.0


In [28]:
print(np.median(marks))

87.0


In [32]:
hours=np.array([2,3,4,5,6,7,8,9,10])
marks=np.array([85, 90,90,80,72,65,78,72,88])
print(np.corrcoef(hours,marks))

[[ 1.         -0.41142733]
 [-0.41142733  1.        ]]


In [34]:
hr=np.array([1,2,3,4])
marks=np.array([100,20,30,40])
print(np.corrcoef(hr,marks))

[[ 1.         -0.61065803]
 [-0.61065803  1.        ]]


In [ ]:
student                     hours   marks 
1                           2       85  
2                           3       90
3                           4       100
4                           5       120

In [39]:
hours=np.array([2,3,4,5])
marks=np.array([85, 40,10,50])
print(np.corrcoef(hours,marks))

[[ 1.         -0.56360186]
 [-0.56360186  1.        ]]


In [41]:
stock_a=np.array([100,105,110,115,120])
stock_b=np.array([200,220,230,59,62])
print(np.corrcoef(stock_a,stock_b))

[[ 1.         -0.80137229]
 [-0.80137229  1.        ]]


In [ ]:
height>weight-- positve correlation
price up and demand low  -- negative correlation
a is not =b -- no correlation

In [42]:
import seaborn as sns
import numpy as np
import pandas as pd
tips = sns.load_dataset('tips')
tipscorr = tips[['total_bill','tip','size']]
tipscorr.corr()

,total_bill,tip,size
total_bill,1.000000,0.675734,0.598315
tip,0.675734,1.000000,0.489299
size,0.598315,0.489299,1.000000


In [44]:
# sorting & searching
marks

array([85, 40, 10, 50])

In [45]:
updated_marks

array([80, 85, 85, 75, 67, 60, 73, 67, 83, 73, 87, 83, 90, 75, 86, 82, 84])

In [46]:
print(np.sort(updated_marks))

[60 67 67 73 73 75 75 80 82 83 83 84 85 85 86 87 90]


In [47]:
print(np.argsort(updated_marks))

[ 5  4  7  6  9  3 13  0 15  8 11 16  1  2 14 10 12]


In [48]:
updated_marks

array([80, 85, 85, 75, 67, 60, 73, 67, 83, 73, 87, 83, 90, 75, 86, 82, 84])

In [65]:
marks=np.array([80,60,90,70])
print(np.argsort(marks))

[1 3 0 2]


In [66]:
print(np.sort(marks))

[60 70 80 90]


In [67]:
print(np.array(marks[np.where(marks>85)]))

[90]


In [68]:
marks

array([80, 60, 90, 70])

In [81]:
updated_array=np.searchsorted(marks,85)

In [82]:
marks

array([80, 60, 90, 70])

In [83]:
updated_array

np.int64(2)

In [80]:
print(marks[updated_array:updated_array+5])

[90 70]


In [76]:
marks

array([80, 60, 90, 70])

In [92]:
arr=np.array([10,50,40,20,35])
value=50
idx=np.searchsorted(arr,value)
print(idx)
new_arr=np.insert(arr,idx,value)
# new_arr=np.insert(arr,2,100)
print(new_arr)


5
[10 50 40 20 35 50]


In [93]:
new_arr

array([10, 50, 40, 20, 35, 50])

In [94]:
student=np.array([1,2,3,4,5,6])
print(student)

[1 2 3 4 5 6]


In [96]:
print(np.split(student,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [99]:
array1=np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [102]:
A=np.hsplit(array1,2)

In [101]:
print(np.vsplit(array1,2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [103]:
A

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [104]:
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
for i in array1:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [106]:
for i in np.nditer(array1):
    print(i)

1
2
3
4
5
6
7
8


In [107]:
dim=np.array([10,2,30])

In [108]:
for i in dim:
    print(i)


10
2
30


In [1]:
# Random Module
import numpy as np
data=np.random.randint(1,101,10)


In [2]:
print(data)

[13  5  5 52 24 89 23 58  4 35]


In [4]:
float_data=np.random.rand(10)

In [5]:
print(float_data)

[0.48660676 0.60070649 0.0513195  0.99200156 0.86852393 0.47495622
 0.94731907 0.88699083 0.03318482 0.23586712]


In [9]:
student=["Raman","Madav","Suresh","Ravi","Vishnu","Kumar","Ramesh","Suresh","Ravi","Vishnu"]
student=np.array(student)
print(np.random.choice(student,3))   

['Ramesh' 'Suresh' 'Ramesh']


In [12]:
cards=np.array([1,2,3,4,5,6])
np.random.shuffle(cards)

In [13]:
print(cards)

[2 5 1 3 6 4]


In [14]:
# Liner Algebra
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


In [ ]:
1*4+2*5+3*6=32
4+10+18=32

In [15]:
A=np.array([
    [1,2],
    [3,4]
])
B=np.array([
    [5,6],
    [7,8]
    ])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [16]:
# Multiplying A and B
print(np.matmul(A,B))

[[19 22]
 [43 50]]


In [17]:
print(np.linalg.det(A))

-2.0000000000000004


In [21]:
# |A|=ad-bc  Formula of Determinant of 2X2 Matrix
A=np.array([
    [1,2],
    [3,4]
])
print(A)
b=np.linalg.det(A)
print(b)

[[1 2]
 [3 4]]
-2.0000000000000004


In [22]:
a=1
b=2
c=3
d=4

In [23]:
data=np.array([
    [1,2],
    [3,4]
])
inverse=np.linalg.inv(data)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
a=1/det(A)[d,-b,
            -c,a]

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3716019895.py, line 1)

In [ ]:
# x+y=5
# 2x+3y=12
# Matrix
# AX=B
# A=[1 1
#    2 3]

# X=[x
#    y]
# b=[5
#     12]
X=A^-1B

In [25]:
value=np.array([4,5,8])
print(np.sqrt(value))

[2.         2.23606798 2.82842712]


In [26]:
print(np.sin(value))

[-0.7568025  -0.95892427  0.98935825]


In [27]:
print(np.cos(value))

[-0.65364362  0.28366219 -0.14550003]


In [28]:
print(np.log(value))

[1.38629436 1.60943791 2.07944154]


In [ ]:
import numpy as np
angle=np.array([0,np.pi/2,np.pi])

In [35]:
a=np.array([np.pi/2])

In [36]:
print(a)

[1.57079633]


In [34]:
22/7/2

1.5714285714285714

In [ ]:
Degree                      Radian                       sin
0                            0()                            0
30                           0.5235987755982988(pi/6)      0.5
45                           0.7853981633974483(pi/4)      0.707106781186
60                           0.86(pi/3)      0.866025403784
90                           1(pi/2)      1.0   

In [37]:
data_deg=np.array([0,30,45,60,90])
print(np.sin(data_deg))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


In [39]:
data_deg=np.array([0,30,45,60,90])
data_rad=np.radians(data_deg)
print(np.sin(data_rad))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [40]:
data_rad=np.radians(data_deg)
print(np.cos(data_rad))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [ ]:
# File Handling
arr=np.array([50,60,80])
np.save("marks.npy",arr)    

In [42]:
data=np.load("marks.npy")

In [43]:
print(data)

[50 60 80]


In [52]:
np.savetxt("marks.csv",arr,delimiter=",")

In [57]:
data_load=np.loadtxt("marks.csv", delimiter=",")

In [59]:
print(data_load.astype(int))

[50 60 80]


In [ ]:
# marks=np.array([85, 90, 78, 92, 88, 95, 80, 91, 87, 89])

1.Total Student
2.Higest Marks
3.Lowset Marks
4/. Average Marks
5. Median Marks
6. standard deviation
7. Toper Position
8. Weak student Position
9. pass Student Marks above 40
10 fail Student Marks below 40
11.Marks >80 distinct show
12 Grace Marks 5 marks above 80
13 Rank 
14. Save CSV    

